import type { NextPage } from 'next';
import Head from 'next/head';
import Container from '../src/components/based/Container';
import Recipe from '../src/components/shared/Recipe';

import { recipe1 } from '../src/constants/recipes';

const Home: NextPage = () => {
	return (
		<Container>
			<Head>
				<title>Camping Menu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			<Recipe {...recipe1} />
		</Container>
	);
};

export default Home;
